test: runtest test5
	echo ok

GCC=gcc-4.7
PLUGIN_SOURCE_FILES= plugin.c 
TOP := $(dir $(lastword $(MAKEFILE_LIST)))
GCCPLUGIN_HEADER_DIR=/usr/lib/gcc/x86_64-linux-gnu/5.1.1/plugin/include
CXX=g++-5
CFLAGS+= -g -O0 -save-temps  -I$(GCCPLUGIN_HEADER_DIR)  -fPIC -O2   -Wl,-E  -fstack-protector -ldl -lm -lpthread -lc -lcrypt

runtest :
	make

test2:
	${CXX} -fplugin=./.libs/template_plugin.so tests/plugincpp_test.cpp

test21:
	${CXX} -c -fplugin=./.libs/template_plugin.so tests/crash1.cpp

test22:
	${CXX} -c -fplugin=./.libs/template_plugin.so tests/plugincpp_interface.cpp

test23:
	${CXX} -c -fplugin=./.libs/template_plugin.so tests/plugincpp_interface_simple.cpp

test7:
	${CXX} -c -fplugin=./.libs/template_plugin.so tests/test_struct.cpp

test3:
	${CXX} -fplugin=./.libs/template_plugin.so -c tests/test.c

test4:
	${CXX} -fplugin=./.libs/template_plugin.so -c tests/test_tree.cpp

test5:
	${CXX} -fplugin=./.libs/template_plugin.so -c tests/test_enum.cpp

test6:
	${CXX} -fplugin=./.libs/template_plugin.so -c tests/test_enum1.cpp

testgen:
	${CXX} -save-temps -Wall -std=gnu++11 tests/test_cpp_out.cpp

clean :
	rm plugin.so
	rm *.o
	rm *.i *.ii *.s

static_test :
	${CXX}  -std=c++0x -I fake fake/tree.c plugincpp.cpp  RecordContext.cpp

distclean:
	- rm *.i *.ii *.s
	- make distclean;
	autoreconf;
	./configure;
	make
