typedef enum tree_code
{
  ERROR_MARK,
  IDENTIFIER_NODE,
  TREE_LIST,
  TREE_VEC,
  BLOCK,
  OFFSET_TYPE,
  ENUMERAL_TYPE,
  BOOLEAN_TYPE,
  INTEGER_TYPE,
  REAL_TYPE,
  POINTER_TYPE,
  REFERENCE_TYPE,
  NULLPTR_TYPE,
  FIXED_POINT_TYPE,
  COMPLEX_TYPE,
  VECTOR_TYPE,
  ARRAY_TYPE,
  RECORD_TYPE,
  UNION_TYPE,
  QUAL_UNION_TYPE,
  VOID_TYPE,
  FUNCTION_TYPE,
  METHOD_TYPE,
  LANG_TYPE,
  INTEGER_CST,
  REAL_CST,
  FIXED_CST,
  COMPLEX_CST,
  VECTOR_CST,
  STRING_CST,
  // ////# 343 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  FUNCTION_DECL,
  LABEL_DECL,
  FIELD_DECL,
  VAR_DECL,
  CONST_DECL,
  PARM_DECL,
  TYPE_DECL,
  RESULT_DECL,
  DEBUG_EXPR_DECL,
  NAMESPACE_DECL,
  // ////# 373 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  IMPORTED_DECL,
  // ////# 383 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  NAMELIST_DECL,
  TRANSLATION_UNIT_DECL,
  // ////# 400 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  COMPONENT_REF,
  // ////# 410 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  BIT_FIELD_REF,
  ARRAY_REF,
  ARRAY_RANGE_REF,
  REALPART_EXPR,
  IMAGPART_EXPR,
  // ////# 439 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  VIEW_CONVERT_EXPR,
  INDIRECT_REF,
  // ////# 451 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  OBJ_TYPE_REF,
  // ////# 470 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  CONSTRUCTOR,
  // ////# 480 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  COMPOUND_EXPR,
  MODIFY_EXPR,
  INIT_EXPR,
  TARGET_EXPR,
  // ////# 510 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  COND_EXPR,
  // ////# 522 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  VEC_COND_EXPR,
  // ////# 536 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  VEC_PERM_EXPR,
  // ////# 559 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  BIND_EXPR,
  CALL_EXPR,
  WITH_CLEANUP_EXPR,
  // ////# 591 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  CLEANUP_POINT_EXPR,
  // ////# 643 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  PLACEHOLDER_EXPR,
  PLUS_EXPR,
  MINUS_EXPR,
  MULT_EXPR,
  POINTER_PLUS_EXPR,
  MULT_HIGHPART_EXPR,
  TRUNC_DIV_EXPR,
  CEIL_DIV_EXPR,
  FLOOR_DIV_EXPR,
  ROUND_DIV_EXPR,
  TRUNC_MOD_EXPR,
  CEIL_MOD_EXPR,
  FLOOR_MOD_EXPR,
  ROUND_MOD_EXPR,
  RDIV_EXPR,
  EXACT_DIV_EXPR,
  FIX_TRUNC_EXPR,
  FLOAT_EXPR,
  NEGATE_EXPR,
  MIN_EXPR,
  MAX_EXPR,
  ABS_EXPR,
  // ////# 717 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  LSHIFT_EXPR,
  RSHIFT_EXPR,
  LROTATE_EXPR,
  RROTATE_EXPR,
  BIT_IOR_EXPR,
  BIT_XOR_EXPR,
  BIT_AND_EXPR,
  BIT_NOT_EXPR,
  // ////# 737 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  TRUTH_ANDIF_EXPR,
  TRUTH_ORIF_EXPR,
  TRUTH_AND_EXPR,
  TRUTH_OR_EXPR,
  TRUTH_XOR_EXPR,
  TRUTH_NOT_EXPR,
  // ////# 753 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  LT_EXPR,
  LE_EXPR,
  GT_EXPR,
  GE_EXPR,
  EQ_EXPR,
  NE_EXPR,
  UNORDERED_EXPR,
  ORDERED_EXPR,
  UNLT_EXPR,
  UNLE_EXPR,
  UNGT_EXPR,
  UNGE_EXPR,
  UNEQ_EXPR,
  LTGT_EXPR,
  RANGE_EXPR,
  PAREN_EXPR,
  CONVERT_EXPR,
  ADDR_SPACE_CONVERT_EXPR,
  FIXED_CONVERT_EXPR,
  NOP_EXPR,
  NON_LVALUE_EXPR,
  COMPOUND_LITERAL_EXPR,
  SAVE_EXPR,
  ADDR_EXPR,
  FDESC_EXPR,
  COMPLEX_EXPR,
  CONJ_EXPR,
  PREDECREMENT_EXPR,
  PREINCREMENT_EXPR,
  POSTDECREMENT_EXPR,
  POSTINCREMENT_EXPR,
  VA_ARG_EXPR,
  TRY_CATCH_EXPR,
  TRY_FINALLY_EXPR,
  DECL_EXPR,
  LABEL_EXPR,
  GOTO_EXPR,
  RETURN_EXPR,
  EXIT_EXPR,
  LOOP_EXPR,
  // ////# 893 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  SWITCH_EXPR,
  // ////# 905 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  CASE_LABEL_EXPR,
  ASM_EXPR,
  SSA_NAME,
  CATCH_EXPR,
  EH_FILTER_EXPR,
  SCEV_KNOWN,
  SCEV_NOT_KNOWN,
  POLYNOMIAL_CHREC,
  STATEMENT_LIST,
  // ////# 961 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  ASSERT_EXPR,
  TREE_BINFO,
  WITH_SIZE_EXPR,
  // ////# 983 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  REALIGN_LOAD_EXPR,
  // ////# 999 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  TARGET_MEM_REF,
  // ////# 1009 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  MEM_REF,
  OMP_PARALLEL,
  OMP_TASK,
  // ////# 1044 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  OMP_FOR,
  OMP_SIMD,
  CILK_SIMD,
  OMP_DISTRIBUTE,
  OMP_TEAMS,
  OMP_TARGET_DATA,
  OMP_TARGET,
  OMP_SECTIONS,
  OMP_SINGLE,
  OMP_SECTION,
  OMP_MASTER,
  OMP_TASKGROUP,
  OMP_ORDERED,
  OMP_CRITICAL,
  OMP_TARGET_UPDATE,
  // ////# 1117 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  OMP_ATOMIC,
  OMP_ATOMIC_READ,
  // ////# 1132 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  OMP_ATOMIC_CAPTURE_OLD,
  OMP_ATOMIC_CAPTURE_NEW,
  OMP_CLAUSE,
  TRANSACTION_EXPR,
  // ////# 1151 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  REDUC_MAX_EXPR,
  REDUC_MIN_EXPR,
  REDUC_PLUS_EXPR,
  // ////# 1164 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  DOT_PROD_EXPR,
  // ////# 1173 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  WIDEN_SUM_EXPR,
  WIDEN_MULT_EXPR,
  // ////# 1189 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  WIDEN_MULT_PLUS_EXPR,
  WIDEN_MULT_MINUS_EXPR,
  // ////# 1205 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  WIDEN_LSHIFT_EXPR,
  FMA_EXPR,
  VEC_LSHIFT_EXPR,
  VEC_RSHIFT_EXPR,
  VEC_WIDEN_MULT_HI_EXPR,
  VEC_WIDEN_MULT_LO_EXPR,
  VEC_WIDEN_MULT_EVEN_EXPR,
  VEC_WIDEN_MULT_ODD_EXPR,
  VEC_UNPACK_HI_EXPR,
  VEC_UNPACK_LO_EXPR,
  VEC_UNPACK_FLOAT_HI_EXPR,
  VEC_UNPACK_FLOAT_LO_EXPR,
  VEC_PACK_TRUNC_EXPR,
  VEC_PACK_SAT_EXPR,
  VEC_PACK_FIX_TRUNC_EXPR,
  // ////# 1265 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree.def"
  VEC_WIDEN_LSHIFT_HI_EXPR,
  VEC_WIDEN_LSHIFT_LO_EXPR,
  PREDICT_EXPR,
  OPTIMIZATION_NODE,
  TARGET_OPTION_NODE,
  ANNOTATE_EXPR,
  CILK_SPAWN_STMT,
  CILK_SYNC_STMT,
  // ////# 2 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  LAST_AND_UNUSED_TREE_CODE,
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/c-family/c-common.def" 1
  // ////# 39 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/c-family/c-common.def"
  C_MAYBE_CONST_EXPR,
  EXCESS_PRECISION_EXPR,
  USERDEF_LITERAL,
  SIZEOF_EXPR,
  ARRAY_NOTATION_REF,
  // ////# 4 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/ada/gcc-interface/ada-tree.def" 1
  // ////# 29 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/ada/gcc-interface/ada-tree.def"
  UNCONSTRAINED_ARRAY_TYPE,
  UNCONSTRAINED_ARRAY_REF,
  NULL_EXPR,
  PLUS_NOMOD_EXPR,
  MINUS_NOMOD_EXPR,
  ATTR_ADDR_EXPR,
  // ////# 62 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/ada/gcc-interface/ada-tree.def"
  STMT_STMT,
  LOOP_STMT,
  EXIT_STMT,
  // ////# 5 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def" 1
  // ////# 41 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  OFFSET_REF,
  PTRMEM_CST,
  NEW_EXPR,
  VEC_NEW_EXPR,
  DELETE_EXPR,
  VEC_DELETE_EXPR,
  SCOPE_REF,
  MEMBER_REF,
  TYPE_EXPR,
  AGGR_INIT_EXPR,
  VEC_INIT_EXPR,
  THROW_EXPR,
  EMPTY_CLASS_EXPR,
  // ////# 107 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  BASELINK,
  // ////# 124 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TEMPLATE_DECL,
  // ////# 159 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TEMPLATE_PARM_INDEX,
  // ////# 168 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TEMPLATE_TEMPLATE_PARM,
  // ////# 177 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TEMPLATE_TYPE_PARM,
  TYPENAME_TYPE,
  TYPEOF_TYPE,
  BOUND_TEMPLATE_TEMPLATE_PARM,
  UNBOUND_CLASS_TEMPLATE,
  USING_DECL,
  USING_STMT,
  DEFAULT_ARG,
  DEFERRED_NOEXCEPT,
  TEMPLATE_ID_EXPR,
  OVERLOAD,
  // ////# 241 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  PSEUDO_DTOR_EXPR,
  MODOP_EXPR,
  CAST_EXPR,
  REINTERPRET_CAST_EXPR,
  CONST_CAST_EXPR,
  STATIC_CAST_EXPR,
  DYNAMIC_CAST_EXPR,
  IMPLICIT_CONV_EXPR,
  DOTSTAR_EXPR,
  TYPEID_EXPR,
  NOEXCEPT_EXPR,
  // ////# 265 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  NON_DEPENDENT_EXPR,
  CTOR_INITIALIZER,
  TRY_BLOCK,
  EH_SPEC_BLOCK,
  HANDLER,
  MUST_NOT_THROW_EXPR,
  CLEANUP_STMT,
  IF_STMT,
  FOR_STMT,
  RANGE_FOR_STMT,
  WHILE_STMT,
  DO_STMT,
  BREAK_STMT,
  CONTINUE_STMT,
  SWITCH_STMT,
  EXPR_STMT,
  TAG_DEFN,
  OFFSETOF_EXPR,
  ARROW_EXPR,
  ALIGNOF_EXPR,
  AT_ENCODE_EXPR,
  STMT_EXPR,
  UNARY_PLUS_EXPR,
  STATIC_ASSERT,
  // ////# 379 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TYPE_ARGUMENT_PACK,
  // ////# 388 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  NONTYPE_ARGUMENT_PACK,
  // ////# 411 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TYPE_PACK_EXPANSION,
  EXPR_PACK_EXPANSION,
  // ////# 430 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  ARGUMENT_PACK_SELECT,
  TRAIT_EXPR,
  // ////# 446 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  LAMBDA_EXPR,
  // ////# 455 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  DECLTYPE_TYPE,
  UNDERLYING_TYPE,
  BASES,
  // ////# 473 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/cp/cp-tree.def"
  TEMPLATE_INFO,
  // ////# 6 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/d/d-tree.def" 1
  // ////# 22 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/d/d-tree.def"
  IASM_EXPR,
  UNSIGNED_RSHIFT_EXPR,
  FLOAT_MOD_EXPR,
  // ////# 7 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/java/java-tree.def" 1
  // ////# 23 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/java/java-tree.def"
  URSHIFT_EXPR,
  COMPARE_EXPR,
  COMPARE_L_EXPR,
  COMPARE_G_EXPR,
  // ////# 8 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 1 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/objc/objc-tree.def" 1
  // ////# 24 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/objc/objc-tree.def"
  CLASS_INTERFACE_TYPE,
  CLASS_IMPLEMENTATION_TYPE,
  CATEGORY_INTERFACE_TYPE,
  CATEGORY_IMPLEMENTATION_TYPE,
  PROTOCOL_INTERFACE_TYPE,
  KEYWORD_DECL,
  INSTANCE_METHOD_DECL,
  CLASS_METHOD_DECL,
  PROPERTY_DECL,
  MESSAGE_SEND_EXPR,
  CLASS_REFERENCE_EXPR,
  // ////# 70 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/objc/objc-tree.def"
  PROPERTY_REF,
  // ////# 8 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/all-tree.def" 2
  // ////# 138 "/usr/lib/gcc/x86_64-linux-gnu/4.9/plugin/include/tree-core.h" 2
  MAX_TREE_CODES
} t_tree_type;

//t_tree_type t;
