

t5.bin: single_objects.cpp tree_nodes.cpp read.cpp iso_tree_node.hpp
	g++ -g single_objects.cpp tree_nodes.cpp read.cpp -o t5.bin

t5: t5.bin
	
	./t5.bin	 ../bin/test_program_segment_6_.out 7fdea1029000 7fdea55aa000 0x7fdea1491780

#0x7fdea1429f70 


t4:
	g++ pointers_objects.cpp tree_nodes.cpp read.cpp
	./a.out	 ../bin/test_program_segment_6_.out 7fdea1029000 7fdea55aa000 2> report.txt


t3:
	g++ pointers.cpp
	#	./a.out ../bin/core > pointers.txt 2>&1
		./a.out	 ../bin/test_program_segment_6_.out 7fdea1029000 7fdea55aa000 2> ../bin/test_program_segment_6_.out.pointers.txt 

t2:
	g++ process.cpp
	./a.out ./bin/core
	# ./a.out	 ./bin/test_program_segment_1__usr_lib_gcc_x86_64-linux-gnu_5_cc1plus.out
	./a.out	 ./bin/test_program_segment_6_.out

t:
	g++ -g test.cpp  dump_memory.cpp
	./a.out